[#insns-prefetch_i,reftext="Cache Block Prefetch for Instruction Fetch"]
=== prefetch.i

Synopsis::
Provide a HINT to hardware that the cache block containing the effective address
is likely to be accessed by an instruction fetch in the near future

Mnemonic::
prefetch.i _offset_(_base_)

Encoding::
[wavedrom, , svg]
....
{reg:[
	{ bits: 7,  name: 0x13,        attr: ['OP-IMM'] },
	{ bits: 5,  name: 0x0,         attr: ['offset[4:0]'] },
	{ bits: 3,  name: 0x6,         attr: ['ORI'] },
	{ bits: 5,  name: 'rs1',       attr: ['base'] },
	{ bits: 5,  name: 0x0,         attr: ['PREFETCH.I'] },
	{ bits: 7, name: 'imm[11:5]',  attr: ['offset[11:5]'] },
]}
....

Description::
A *prefetch.i* instruction indicates to hardware that the cache block containing
the effective address is likely to be accessed by an instruction fetch in the
near future.

****

_An implementation may opt to cache a copy of the cache block in a cache
accessed by an instruction fetch in order to improve memory access latency, but
this behavior is not required._

****

Operation::
[source,sail]
--
TODO
--
