[#Zicbom,reftext="Cache-Block Management Instructions"]
=== Cache-Block Management Instructions

Cache-block management instructions enable software running on a set of coherent
agents to communicate with a set of non-coherent agents by performing one of the
following operations:

* An _invalidate operation_ makes store operations from a set of non-coherent
  agents appear to the set of coherent agents at a point common to both
  sets by removing all copies of a cache block from the coherent caches up to
  that point
  
* A _clean operation_ makes store operations from the set of coherent agents
  appear to a set of non-coherent agents at a point common to both sets by
  performing a write operation of a copy of a cache block to that point,
  provided a coherent agent performed a store operation to the cache block
  since the previous such write operation
  
* A _flush operation_ atomically performs a clean operation followed by an
  invalidate operation

In the Zicbom extension, the instructions operate to a point common to _all_
agents in the system. In other words, an invalidate operation ensures that store
operations from all non-coherent agents appear to agents in the set of coherent
agents, and a clean operation ensures that store operations from coherent agents
appear to all non-coherent agents.

****

_The Zicbom extension does not prohibit agents that fall outside of the above
architectural definition; however, software cannot rely on the defined cache
operations to have the desired effects with respect to those agents._

_Future extensions may define different sets of agents for the purposes of
performance optimization._

****

The following instructions comprise the Zicbom extension:

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|cbo.clean _base_
|<<#insns-cbo_clean>>

|&#10003;
|&#10003;
|cbo.flush _base_
|<<#insns-cbo_flush>>

|&#10003;
|&#10003;
|cbo.inval _base_
|<<#insns-cbo_inval>>

|===
